//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kargo_takip1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelenKargoTakip
    {
        public int Id { get; set; }
        public Nullable<int> kargoID { get; set; }
        public Nullable<int> teslimAlanID { get; set; }
        public Nullable<System.DateTime> gelenTarih { get; set; }
        public string irsaliyeNo { get; set; }
        public string durum { get; set; }
        public Nullable<int> kontrolEdenID { get; set; }
        public Nullable<int> gonderenSirketID { get; set; }
        public Nullable<int> urunID { get; set; }
    
        public virtual KargoFirmaları KargoFirmaları { get; set; }
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        public virtual Kullanıcılar Kullanıcılar1 { get; set; }
        public virtual Sirketler Sirketler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
