//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kargo_takip1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KargoFirmaları
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KargoFirmaları()
        {
            this.GelenKargoTakip = new HashSet<GelenKargoTakip>();
            this.GidenKargoTakip = new HashSet<GidenKargoTakip>();
        }
    
        public int Id { get; set; }
        public string KargoAdi { get; set; }
        public string KargoilgiliKisi { get; set; }
        public string KargoTelNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GelenKargoTakip> GelenKargoTakip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GidenKargoTakip> GidenKargoTakip { get; set; }
    }
}
