//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kargo_takip1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adminEntities : DbContext
    {
        public adminEntities()
            : base("name=adminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GelenKargoTakip> GelenKargoTakip { get; set; }
        public virtual DbSet<GidenKargoTakip> GidenKargoTakip { get; set; }
        public virtual DbSet<gidenUrunlerBilgi> gidenUrunlerBilgi { get; set; }
        public virtual DbSet<KargoFirmaları> KargoFirmaları { get; set; }
        public virtual DbSet<Kullanıcılar> Kullanıcılar { get; set; }
        public virtual DbSet<Sirketler> Sirketler { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
    }
}
