//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kargo_takip1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sirketler()
        {
            this.GelenKargoTakip = new HashSet<GelenKargoTakip>();
            this.GidenKargoTakip = new HashSet<GidenKargoTakip>();
            this.gidenUrunlerBilgi = new HashSet<gidenUrunlerBilgi>();
        }
    
        public int Id { get; set; }
        public string sirketAdi { get; set; }
        public string sirketAdresi { get; set; }
        public string vergiNo { get; set; }
        public string vergiDairesi { get; set; }
        public string telefonNo { get; set; }
        public string ilgiliKisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GelenKargoTakip> GelenKargoTakip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GidenKargoTakip> GidenKargoTakip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gidenUrunlerBilgi> gidenUrunlerBilgi { get; set; }
    }
}
