//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kargo_takip1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kargoHareket
    {
        public int ıd { get; set; }
        public Nullable<int> kargoId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> gonderenId { get; set; }
        public Nullable<int> alanId { get; set; }
        public string irsaliyeNumarasi { get; set; }
        public Nullable<System.DateTime> gonderilenTarih { get; set; }
        public Nullable<System.DateTime> gelenTarih { get; set; }
        public string Durum { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> alanKullanıcıId { get; set; }
        public Nullable<int> gonderenKullancıId { get; set; }
    
        public virtual kargolar kargolar { get; set; }
        public virtual kullanıcılar kullanıcılar { get; set; }
        public virtual kullanıcılar kullanıcılar1 { get; set; }
        public virtual sirketler sirketler { get; set; }
        public virtual sirketler sirketler1 { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
