//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kargo_takip1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class goratakipEntities1 : DbContext
    {
        public goratakipEntities1()
            : base("name=goratakipEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kargoHareket> kargoHareket { get; set; }
        public virtual DbSet<kargolar> kargolar { get; set; }
        public virtual DbSet<kullanıcılar> kullanıcılar { get; set; }
        public virtual DbSet<sirketler> sirketler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
    }
}
