//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kargo_takip1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GidenKargoTakip
    {
        public int Id { get; set; }
        public Nullable<int> kargoID { get; set; }
        public Nullable<int> gidenFirmaID { get; set; }
        public Nullable<System.DateTime> gonderilenTarih { get; set; }
        public Nullable<int> gonderenKisi { get; set; }
        public string acıklama { get; set; }
        public string irsaliyeNo { get; set; }
        public Nullable<int> urunID { get; set; }
    
        public virtual KargoFirmaları KargoFirmaları { get; set; }
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        public virtual Sirketler Sirketler { get; set; }
        public virtual gidenUrunlerBilgi gidenUrunlerBilgi { get; set; }
    }
}
